export const ENDPOINTS = {
  register: "/api/auth/register",
  login: "/api/auth/login",
  me: "/api/auth/me",
  gearList: "/api/gear",
  gearDetail: (id: string) => `/api/gear/${id}`,
  categories: "/api/gear/categories",
  myRentals: "/api/rentals/rentals",
  rentalDetail: (id: string) => `/api/rentals/rentals/${id}`,
  createRental: "/api/rentals/gear",
  createReview: "/api/reviews",
  createCheckout: "/api/payments/create",
  confirmPayment: "/api/payments/confirm",
  payments: "/api/payments",
  paymentDetail: (id: string) => `/api/payments/${id}`,
  providerAddGear: "/api/provider/gear",
  providerUpdateGear: (id: string) => `/api/provider/gear/${id}`,
  providerDeleteGear: (id: string) => `/api/provider/gear/${id}`,
  providerOrders: "/api/provider/orders",
  providerUpdateOrder: (id: string) => `/api/provider/orders/${id}`,
  adminUsers: "/api/admin/users",
  adminUpdateUser: (id: string) => `/api/admin/users/${id}`,
  adminGear: "/api/admin/gear",
  adminRentals: "/api/admin/rentals",
} as const;
